### ISSUE TITLE
[fix] : unnecessary fetchs

### ISSUE THREAD

**Issue by SantiagoZarate** [Devansh-365/ceddit#1]
I've noticed the application makes unnecessarys fetchs to the API when browse to _explore_ and _single post_ pages. It can cause bad performance.

![Screenshot (53)](https://github.com/Devansh-365/ceddit/assets/125758863/f179ed0b-3b30-4625-bb0f-beecb40ad456)

**Comment by Devansh-365** [comment]
thanks, for letting me know. Will fix that issue.
