### ISSUE TITLE
Sorting Issue with Posts

### ISSUE THREAD

**Issue by SuryanshBVerma** [Devansh-365/ceddit#9]
#### Issue Description:

Highlighting an issue I've encountered while using the sortby feature in the project. Despite utilizing the "sortby" feature, the posts within the project are not being sorted as expected.

#### Expected Behavior:

Upon employing the sortby feature, the posts should ideally be arranged in the specified order. However, the sorting mechanism does not seem to be working at the moment.

#### Actual Behavior:

Currently, upon selecting the sortby criteria, the page does not reflect the desired changes.

#### Steps to Reproduce:
```
Navigate to the explore page.
Select any cirteria under the sortby options.
Observe that the posts are not sorted.
```

**Comment by Devansh-365** [comment]
Hi @SuryanshBVerma , Thank you for reporting the issue. If you're interested in addressing this, I can assign this issue to you.

**Comment by SuryanshBVerma** [comment]
Hi @Devansh-365, 

Yes, I am indeed interested in addressing the issue. But, I want to have a brief conversation before handling this, as I am very new to contributing to codes like this and need to learn about the standards to follow. I will be dropping you a personal email.

Thank You.
